# Generated by Django 3.0.2 on 2020-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activitylog', '0002_remove_activityperiod_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
