# Generated by Django 3.0.2 on 2020-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activitylog', '0003_auto_20200331_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
